### ISSUE TITLE
Unexpected uppercase styling

### ISSUE THREAD

**Issue by yanniboi** [spherehq/sphere#50]
# Feature Request

*Not really a feature, more of a question...*

**Package version:**

  @spherehq/cli/0.7.2 linux-x64 node-v12.0.0

**Link**
https://sphere.sh/@yanniboi/29-04-19

**Describe the Feature Request**

How do I control the uppercase style on list items. Am I doing something wrong?

```
- Its always annoying not knowing if there is a problem in the booking system or if staff are just doing something wrong. It would be nice to have tickets extend RevisionableContentEntityBase so we could get a log of revision users which will help identify tickets that staff have messed with.

 >  I think if we're going to do something like that, I'd rather go down the messages route (audit trail type approach)
Though that would only capture key details not everything
```
sourcecode

![Selection_030](https://user-images.githubusercontent.com/1744957/56943655-6dfa0600-6b18-11e9-8f77-2cb915a395f3.png)

```css

.gLWptl {
   ...
    letter-spacing: 1px;
    text-transform: uppercase;
    color: rgb(37, 29, 43);
   ...
}
```

**Describe Preferred Solution**

...
**Describe Alternatives**

...
**Related Code**

...
**Additional Context**

...

**Comment by jjaybrown** [comment]
This is a default style for the platform.
